name: endolas
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.1.5
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cloudpickle=1.5.0
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.20.0
  - dbus=1.13.16
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.0
  - freetype=2.10.2
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - imageio=2.9.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2020.1
  - ipykernel=5.3.3
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.1
  - jinja2=2.11.2
  - joblib=0.16.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.6
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - llvmlite=0.34.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - networkx=2.4
  - notebook=6.0.3
  - numba=0.51.2
  - numpy=1.18.5
  - numpy-base=1.18.5
  - olefile=0.46
  - openssl=1.1.1h
  - pandas=1.0.5
  - pandoc=2.10
  - pandocfilters=1.4.2
  - parso=0.7.0
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.1.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - python=3.8.2
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyzmq=19.0.1
  - qt=5.9.7
  - qtconsole=4.7.5
  - qtpy=1.9.0
  - readline=8.0
  - scikit-image=0.16.2
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=49.2.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.32.3
  - statsmodels=0.11.1
  - tbb=2020.3
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - umap-learn=0.4.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.9.0
    - alabaster==0.7.12
    - albumentations==0.4.5
    - ansiwrap==0.8.4
    - appdirs==1.4.4
    - astunparse==1.6.3
    - async-generator==1.10
    - babel==2.8.0
    - black==19.10b0
    - cachetools==4.1.0
    - chardet==3.0.4
    - click==7.1.2
    - docutils==0.16
    - efficientnet==1.0.0
    - gast==0.3.3
    - google-auth==1.14.1
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.28.1
    - h5py==2.10.0
    - idna==2.9
    - image-classifiers==1.0.0
    - imageio-ffmpeg==0.4.2
    - imagesize==1.2.0
    - imgaug==0.2.6
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.2.1
    - nbclient==0.4.1
    - nest-asyncio==1.4.0
    - nibabel==3.1.0
    - oauthlib==3.1.0
    - opencv-python-headless==4.2.0.34
    - opt-einsum==3.2.1
    - packaging==20.3
    - papermill==2.1.2
    - pathspec==0.8.0
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyyaml==5.3.1
    - regex==2020.7.14
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - segmentation-models==1.0.1
    - snowballstemmer==2.0.0
    - sphinx==3.2.1
    - sphinx-rtd-theme==0.5.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - tenacity==6.2.0
    - tensorboard==2.2.1
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorflow==2.2.0rc3
    - tensorflow-estimator==2.2.0
    - termcolor==1.1.0
    - textwrap3==0.9.2
    - toml==0.10.1
    - tqdm==4.48.0
    - typed-ast==1.4.1
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - wrapt==1.12.1

